name: Deploy to Staging

on:
  push:
    branches:
      - main  # Déploiement à chaque push sur main

env:
  DEPLOY_ENV: staging
  MAINTAINER_NAME: "Azza Dev"
  MAINTAINER_EMAIL: "azzabensalem8@gmail.com"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🛠️ Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Install dependencies
        run: npm install

      - name: ✅ Run tests
        run: npm test

  deploy:
    name: 🚀 Deploy to Staging
    runs-on: ubuntu-latest
    needs: test  # Ce job ne s’exécute que si les tests passent

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🛠️ Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🔧 Build the project
        run: npm run build

      - name: 📡 Deploy to staging server
        env:
          SERVER: ${{ secrets.STAGING_SERVER }}
          USER: ${{ secrets.SSH_USER }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "Déploiement en cours vers $SERVER..."
          mkdir -p logs
          echo "Déploiement réussi !" > logs/deploy.log
          # Exemple : scp -i $KEY -r dist/* $USER@$SERVER:/var/www/staging/

      - name: 📤 Upload deploy logs
        uses: actions/upload-artifact@v3
        with:
          name: deploy-logs
          path: logs/deploy.log

      - name: ℹ️ Afficher les coordonnées
        run: |
          echo "------------------------"
          echo "👤 Coordonnées du mainteneur"
          echo "Nom      : $MAINTAINER_NAME"
          echo "Email    : $MAINTAINER_EMAIL"
          echo "Téléphone: +21642201428"
          echo "Ville    : Monastir"
          echo "LinkedIn : linkedin.com/in/azza-dev"
          echo "------------------------"

      # Optionnel : Notification Slack (nécessite configuration du secret SLACK_WEBHOOK_URL)
      - name: 🔔 Slack Notification
        if: success()
        uses: Ilshidur/action-slack@v2
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: "✅ Déploiement terminé avec succès pour Azza Dev sur *staging* !"

